// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante2_114cc3ed38204b23aa7bbcb458232ee4 = new Entity("pulsante_2")
engine.addEntity(pulsante2_114cc3ed38204b23aa7bbcb458232ee4)
const pulsante2_114cc3ed38204b23aa7bbcb458232ee4_transform = new Transform({
  position: new Vector3(16.7, 2.1, 3.56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante2_114cc3ed38204b23aa7bbcb458232ee4.addComponentOrReplace(pulsante2_114cc3ed38204b23aa7bbcb458232ee4_transform)
const pulsante2_114cc3ed38204b23aa7bbcb458232ee4_boxShape = new BoxShape()
pulsante2_114cc3ed38204b23aa7bbcb458232ee4.addComponentOrReplace(pulsante2_114cc3ed38204b23aa7bbcb458232ee4_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante3_2f39993797bd41b9bbee7074dc143471 = new Entity("pulsante_3")
engine.addEntity(pulsante3_2f39993797bd41b9bbee7074dc143471)
const pulsante3_2f39993797bd41b9bbee7074dc143471_transform = new Transform({
  position: new Vector3(16.7, 2.1, 3.91),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante3_2f39993797bd41b9bbee7074dc143471.addComponentOrReplace(pulsante3_2f39993797bd41b9bbee7074dc143471_transform)
const pulsante3_2f39993797bd41b9bbee7074dc143471_boxShape = new BoxShape()
pulsante3_2f39993797bd41b9bbee7074dc143471.addComponentOrReplace(pulsante3_2f39993797bd41b9bbee7074dc143471_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante4_b883e1c7009e4c04a392195e71bf51f8 = new Entity("pulsante_4")
engine.addEntity(pulsante4_b883e1c7009e4c04a392195e71bf51f8)
const pulsante4_b883e1c7009e4c04a392195e71bf51f8_transform = new Transform({
  position: new Vector3(16.7, 1.83, 3.18),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante4_b883e1c7009e4c04a392195e71bf51f8.addComponentOrReplace(pulsante4_b883e1c7009e4c04a392195e71bf51f8_transform)
const pulsante4_b883e1c7009e4c04a392195e71bf51f8_boxShape = new BoxShape()
pulsante4_b883e1c7009e4c04a392195e71bf51f8.addComponentOrReplace(pulsante4_b883e1c7009e4c04a392195e71bf51f8_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante5_89fda61333404f8f8cb6068273ec0d3c = new Entity("pulsante_5")
engine.addEntity(pulsante5_89fda61333404f8f8cb6068273ec0d3c)
const pulsante5_89fda61333404f8f8cb6068273ec0d3c_transform = new Transform({
  position: new Vector3(16.7, 1.83, 3.56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante5_89fda61333404f8f8cb6068273ec0d3c.addComponentOrReplace(pulsante5_89fda61333404f8f8cb6068273ec0d3c_transform)
const pulsante5_89fda61333404f8f8cb6068273ec0d3c_boxShape = new BoxShape()
pulsante5_89fda61333404f8f8cb6068273ec0d3c.addComponentOrReplace(pulsante5_89fda61333404f8f8cb6068273ec0d3c_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante6_dcc0deedc56646f2a899a8851cc154b5 = new Entity("pulsante_6")
engine.addEntity(pulsante6_dcc0deedc56646f2a899a8851cc154b5)
const pulsante6_dcc0deedc56646f2a899a8851cc154b5_transform = new Transform({
  position: new Vector3(16.7, 1.83, 3.91),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante6_dcc0deedc56646f2a899a8851cc154b5.addComponentOrReplace(pulsante6_dcc0deedc56646f2a899a8851cc154b5_transform)
const pulsante6_dcc0deedc56646f2a899a8851cc154b5_boxShape = new BoxShape()
pulsante6_dcc0deedc56646f2a899a8851cc154b5.addComponentOrReplace(pulsante6_dcc0deedc56646f2a899a8851cc154b5_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5 = new Entity("pulsante_7")
engine.addEntity(pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5)
const pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5_transform = new Transform({
  position: new Vector3(16.7, 1.56, 3.18),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5.addComponentOrReplace(pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5_transform)
const pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5_boxShape = new BoxShape()
pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5.addComponentOrReplace(pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante8_d22f4e509279498cbd0b15b5c545a733 = new Entity("pulsante_8")
engine.addEntity(pulsante8_d22f4e509279498cbd0b15b5c545a733)
const pulsante8_d22f4e509279498cbd0b15b5c545a733_transform = new Transform({
  position: new Vector3(16.7, 1.56, 3.56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante8_d22f4e509279498cbd0b15b5c545a733.addComponentOrReplace(pulsante8_d22f4e509279498cbd0b15b5c545a733_transform)
const pulsante8_d22f4e509279498cbd0b15b5c545a733_boxShape = new BoxShape()
pulsante8_d22f4e509279498cbd0b15b5c545a733.addComponentOrReplace(pulsante8_d22f4e509279498cbd0b15b5c545a733_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante9_55d696ae0fac486cb06038bc7fee3481 = new Entity("pulsante_9")
engine.addEntity(pulsante9_55d696ae0fac486cb06038bc7fee3481)
const pulsante9_55d696ae0fac486cb06038bc7fee3481_transform = new Transform({
  position: new Vector3(16.7, 1.56, 3.91),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante9_55d696ae0fac486cb06038bc7fee3481.addComponentOrReplace(pulsante9_55d696ae0fac486cb06038bc7fee3481_transform)
const pulsante9_55d696ae0fac486cb06038bc7fee3481_boxShape = new BoxShape()
pulsante9_55d696ae0fac486cb06038bc7fee3481.addComponentOrReplace(pulsante9_55d696ae0fac486cb06038bc7fee3481_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante1_4a5251eda1654c90b7605b8a96ad0a23 = new Entity("pulsante_1")
engine.addEntity(pulsante1_4a5251eda1654c90b7605b8a96ad0a23)
const pulsante1_4a5251eda1654c90b7605b8a96ad0a23_transform = new Transform({
  position: new Vector3(16.7, 2.1, 3.18),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante1_4a5251eda1654c90b7605b8a96ad0a23.addComponentOrReplace(pulsante1_4a5251eda1654c90b7605b8a96ad0a23_transform)
const pulsante1_4a5251eda1654c90b7605b8a96ad0a23_boxShape = new BoxShape()
pulsante1_4a5251eda1654c90b7605b8a96ad0a23.addComponentOrReplace(pulsante1_4a5251eda1654c90b7605b8a96ad0a23_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsante0_950e9e53d6de49e18f36fcf0b3942a5c = new Entity("pulsante_0")
engine.addEntity(pulsante0_950e9e53d6de49e18f36fcf0b3942a5c)
const pulsante0_950e9e53d6de49e18f36fcf0b3942a5c_transform = new Transform({
  position: new Vector3(16.7, 1.3, 3.56),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsante0_950e9e53d6de49e18f36fcf0b3942a5c.addComponentOrReplace(pulsante0_950e9e53d6de49e18f36fcf0b3942a5c_transform)
const pulsante0_950e9e53d6de49e18f36fcf0b3942a5c_boxShape = new BoxShape()
pulsante0_950e9e53d6de49e18f36fcf0b3942a5c.addComponentOrReplace(pulsante0_950e9e53d6de49e18f36fcf0b3942a5c_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2 = new Entity("pulsante_conferma")
engine.addEntity(pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2)
const pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2_transform = new Transform({
  position: new Vector3(16.7, 1.3, 3.91),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2.addComponentOrReplace(pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2_transform)
const pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2_boxShape = new BoxShape()
pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2.addComponentOrReplace(pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const pulsantereset_13680daf5ccc406f873950dea8d1ea76 = new Entity("pulsante_reset")
engine.addEntity(pulsantereset_13680daf5ccc406f873950dea8d1ea76)
const pulsantereset_13680daf5ccc406f873950dea8d1ea76_transform = new Transform({
  position: new Vector3(16.7, 1.3, 3.18),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(0.1, 0.1, 0.2)
})
pulsantereset_13680daf5ccc406f873950dea8d1ea76.addComponentOrReplace(pulsantereset_13680daf5ccc406f873950dea8d1ea76_transform)
const pulsantereset_13680daf5ccc406f873950dea8d1ea76_boxShape = new BoxShape()
pulsantereset_13680daf5ccc406f873950dea8d1ea76.addComponentOrReplace(pulsantereset_13680daf5ccc406f873950dea8d1ea76_boxShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const corridoio2_b6cfe7f5714d431f8478490726b94026 = new Entity("corridoio2")
engine.addEntity(corridoio2_b6cfe7f5714d431f8478490726b94026)
const corridoio2_b6cfe7f5714d431f8478490726b94026_transform = new Transform({
  position: new Vector3(10.25, 0, 4.1),
  rotation: new Quaternion(0, 0.7071068, 0, 0.7071068),
  scale: new Vector3(1.2, 0.9, 1)
})
corridoio2_b6cfe7f5714d431f8478490726b94026.addComponentOrReplace(corridoio2_b6cfe7f5714d431f8478490726b94026_transform)
const corridoio2_b6cfe7f5714d431f8478490726b94026_GLTFShape = new GLTFShape("models/corridoio2.glb")
corridoio2_b6cfe7f5714d431f8478490726b94026_GLTFShape.withCollisions = true
corridoio2_b6cfe7f5714d431f8478490726b94026_GLTFShape.isPointerBlocker = true
corridoio2_b6cfe7f5714d431f8478490726b94026_GLTFShape.visible = true
corridoio2_b6cfe7f5714d431f8478490726b94026.addComponentOrReplace(corridoio2_b6cfe7f5714d431f8478490726b94026_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY

const stanza3_14dfea898ea54d8182e07d99aec26dd8 = new Entity("stanza3")
engine.addEntity(stanza3_14dfea898ea54d8182e07d99aec26dd8)
const stanza3_14dfea898ea54d8182e07d99aec26dd8_transform = new Transform({
  position: new Vector3(13, -0.2, 4),
  rotation: new Quaternion(0, 0, 0, 1),
  scale: new Vector3(2, 2, 2)
})
stanza3_14dfea898ea54d8182e07d99aec26dd8.addComponentOrReplace(stanza3_14dfea898ea54d8182e07d99aec26dd8_transform)
const stanza3_14dfea898ea54d8182e07d99aec26dd8_GLTFShape = new GLTFShape("models/stanza3.glb")
stanza3_14dfea898ea54d8182e07d99aec26dd8_GLTFShape.withCollisions = true
stanza3_14dfea898ea54d8182e07d99aec26dd8_GLTFShape.isPointerBlocker = true
stanza3_14dfea898ea54d8182e07d99aec26dd8_GLTFShape.visible = true
stanza3_14dfea898ea54d8182e07d99aec26dd8.addComponentOrReplace(stanza3_14dfea898ea54d8182e07d99aec26dd8_GLTFShape)

// FILE WAS GENERATED BY DCL-EDIT
// DO NOT MODIFY




export let scene = {
  pulsante2:{
    entity: pulsante2_114cc3ed38204b23aa7bbcb458232ee4,
    transform: pulsante2_114cc3ed38204b23aa7bbcb458232ee4_transform,
    boxShape: pulsante2_114cc3ed38204b23aa7bbcb458232ee4_boxShape,
  },
  pulsante3:{
    entity: pulsante3_2f39993797bd41b9bbee7074dc143471,
    transform: pulsante3_2f39993797bd41b9bbee7074dc143471_transform,
    boxShape: pulsante3_2f39993797bd41b9bbee7074dc143471_boxShape,
  },
  pulsante4:{
    entity: pulsante4_b883e1c7009e4c04a392195e71bf51f8,
    transform: pulsante4_b883e1c7009e4c04a392195e71bf51f8_transform,
    boxShape: pulsante4_b883e1c7009e4c04a392195e71bf51f8_boxShape,
  },
  pulsante5:{
    entity: pulsante5_89fda61333404f8f8cb6068273ec0d3c,
    transform: pulsante5_89fda61333404f8f8cb6068273ec0d3c_transform,
    boxShape: pulsante5_89fda61333404f8f8cb6068273ec0d3c_boxShape,
  },
  pulsante6:{
    entity: pulsante6_dcc0deedc56646f2a899a8851cc154b5,
    transform: pulsante6_dcc0deedc56646f2a899a8851cc154b5_transform,
    boxShape: pulsante6_dcc0deedc56646f2a899a8851cc154b5_boxShape,
  },
  pulsante7:{
    entity: pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5,
    transform: pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5_transform,
    boxShape: pulsante7_8f02b6c4bc2d4f57be3e002c38ebd0e5_boxShape,
  },
  pulsante8:{
    entity: pulsante8_d22f4e509279498cbd0b15b5c545a733,
    transform: pulsante8_d22f4e509279498cbd0b15b5c545a733_transform,
    boxShape: pulsante8_d22f4e509279498cbd0b15b5c545a733_boxShape,
  },
  pulsante9:{
    entity: pulsante9_55d696ae0fac486cb06038bc7fee3481,
    transform: pulsante9_55d696ae0fac486cb06038bc7fee3481_transform,
    boxShape: pulsante9_55d696ae0fac486cb06038bc7fee3481_boxShape,
  },
  pulsante1:{
    entity: pulsante1_4a5251eda1654c90b7605b8a96ad0a23,
    transform: pulsante1_4a5251eda1654c90b7605b8a96ad0a23_transform,
    boxShape: pulsante1_4a5251eda1654c90b7605b8a96ad0a23_boxShape,
  },
  pulsante0:{
    entity: pulsante0_950e9e53d6de49e18f36fcf0b3942a5c,
    transform: pulsante0_950e9e53d6de49e18f36fcf0b3942a5c_transform,
    boxShape: pulsante0_950e9e53d6de49e18f36fcf0b3942a5c_boxShape,
  },
  pulsanteconferma:{
    entity: pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2,
    transform: pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2_transform,
    boxShape: pulsanteconferma_3b2944c8c4dc438386f6b4b407cf94b2_boxShape,
  },
  pulsantereset:{
    entity: pulsantereset_13680daf5ccc406f873950dea8d1ea76,
    transform: pulsantereset_13680daf5ccc406f873950dea8d1ea76_transform,
    boxShape: pulsantereset_13680daf5ccc406f873950dea8d1ea76_boxShape,
  },
  stanza3:{
    entity: stanza3_14dfea898ea54d8182e07d99aec26dd8,
    transform: stanza3_14dfea898ea54d8182e07d99aec26dd8_transform,
    GLTFShape: stanza3_14dfea898ea54d8182e07d99aec26dd8_GLTFShape,
  },
}

